
drop database inventory_project;
CREATE DATABASE INVENTORY_PROJECT;

USE INVENTORY_PROJECT;

CREATE TABLE Supplied_Products_1
(ProductID INT PRIMARY KEY ,
SupplierUnitPrice DECIMAL(10,2),
Product_Category VARCHAR(150),
Quantity INT,
Supplier_ID INT REFERENCES Supplied_Products_2(Supplier_ID))
engine = InnoDB;


CREATE TABLE Supplied_Products_2
(Supplier_ID INT PRIMARY KEY,
Supplier_Name VARCHAR(150))
engine = InnoDB;



CREATE TABLE Products_Supplied_to_Warehouse
(WAREHOUSE_ID INT REFERENCES WAREHOUSE_ADDRESS_DETAILS(WAREHOUSE_ID),
ProductID INT REFERENCES Supplied_Products_1(ProductID),
SuppliedDate DATE)
engine = InnoDB;



CREATE TABLE WAREHOUSE_ADDRESS_DETAILS
(WAREHOUSE_ID INT PRIMARY KEY,
COUNTRY VARCHAR(150),
STATE VARCHAR(150),
ADDRESS1 VARCHAR(150),
ADDRESS2 VARCHAR(150),
MANAGERID INT REFERENCES EMP_DETAILS(EMP_ID))
engine = InnoDB;

 

CREATE TABLE STORED_PRODUCTS
(PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_CATEGORY VARCHAR(150),
SELLING_UNIT_PRICE DECIMAL(10,2),
QUANTITY INT,
WAREHOUSEID INT REFERENCES WAREHOUSE_ADDRESS_DETAILS(WAREHOUSE_ID))
engine = InnoDB;

CREATE TABLE ORDER_Price (
  TOTAL_PRICE  DECIMAL (10,2), 
  ORDER_ID INT PRIMARY KEY,
  SHIPPING_price DECIMAL (10,2))
  engine = InnoDB;



CREATE TABLE ORDER_Product (
  ORDER_ID  INT , 
  PRODUCT_ID INT ,
  Quantity INT,
  FOREIGN KEY ( ORDER_ID ) REFERENCES ORDER_Price( ORDER_ID ),
FOREIGN KEY ( PRODUCT_ID ) REFERENCES  Stored_Products(PRODUCT_ID ))
engine = InnoDB;


CREATE TABLE ORDER_FullfilimentDate (
  ORDER_ID  INT , 
  PRODUCT_ID INT,
  FULFILS_DATE DATE,
  FOREIGN KEY ( ORDER_ID ) REFERENCES ORDER_Price( ORDER_ID ),
FOREIGN KEY ( PRODUCT_ID ) REFERENCES  Stored_Products(PRODUCT_ID ))
engine = InnoDB;


CREATE TABLE Customer_PlacementDate (
  CuSTOMER_ID INT, 
  ORDER_ID INT PRIMARY KEY,
  PLACE_DATE DATE,
  FOREIGN KEY ( CuSTOMER_ID ) REFERENCES Customer_UserDetails( CuSTOMER_ID ),
  FOREIGN KEY ( ORDER_ID ) REFERENCES ORDER_Price( ORDER_ID ))
  engine = InnoDB;


CREATE TABLE Customer_Email (
  CuSTOMER_ID INT, 
  EMAIL_ADDRESS VARCHAR(150) ,
  FOREIGN KEY ( CuSTOMER_ID ) REFERENCES Customer_UserDetails( CuSTOMER_ID ))
  engine = InnoDB;


CREATE TABLE Customer_Address (
  CuSTOMER_ID INT PRIMARY KEY , 
  ADDRESS VARCHAR(150) ,
  FOREIGN KEY ( CuSTOMER_ID ) REFERENCES Customer_UserDetails( CuSTOMER_ID ))
  engine = InnoDB;



CREATE TABLE EMPLOYEE_DEPENDANCIES
(EMP_ID INT,
NAME VARCHAR(100),
RELATIONSHIP VARCHAR(50),
BIRTHDAY DATE,
SEX VARCHAR(20),
PRIMARY KEY  (EMP_ID,NAME),
FOREIGN KEY (EMP_ID) REFERENCES EMP_DETAILS(EMP_ID))
engine = InnoDB;

CREATE TABLE EMP_DETAILS
(EMP_ID INT ,
SALARY DECIMAL(10,2),
NAME VARCHAR(100),
WAREHOUSE_ID INT,
PRIMARY KEY (EMP_ID),
FOREIGN KEY (WAREHOUSE_ID) REFERENCES  WAREHOUSE_ADDRESS_DETAILS(WAREHOUSE_ID))
engine = InnoDB;


CREATE TABLE ADDRESS_EMP 
(EMP_ID INT,
ADDRESS_1 VARCHAR(100),
ADDRESS_2 VARCHAR(100),
FOREIGN KEY (EMP_ID) REFERENCES EMP_DETAILS(EMP_ID))
engine = InnoDB;


CREATE TABLE MANAGES
(EMP_ID INT,
BONUS DECIMAL(10,2),
FOREIGN KEY (EMP_ID) REFERENCES EMP_DETAILS(EMP_ID))
engine = InnoDB;

CREATE TABLE NON_MANAGERS
(EMP_ID INT,
PERKS DECIMAL(10,2),
FOREIGN KEY (EMP_ID) REFERENCES EMP_DETAILS(EMP_ID))
engine = InnoDB;


CREATE TABLE Customer_UserDetails (
CuSTOMER_ID INT PRIMARY KEY , 
USER_NAME VARCHAR(150) ,
c_PASSWORD  VARCHAR(150))
engine = InnoDB;



UPDATE WAREHOUSE_ADDRESS_DETAILS
SET MANAGERID = WAREHOUSE_ID -1 
WHERE WAREHOUSE_ID < 11;
